// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(__SYM__interrupt,0,0);
        VL_IN8(imem_ready,0,0);
        VL_OUT8(dmem_read,0,0);
        VL_OUT8(dmem_write,0,0);
        VL_IN8(dmem_ready,0,0);
        VL_OUT8(pipeline_stall,0,0);
        CData/*0:0*/ cpu_top__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__reset;
        CData/*0:0*/ cpu_top__DOT__interrupt;
        CData/*0:0*/ cpu_top__DOT__imem_ready;
        CData/*0:0*/ cpu_top__DOT__dmem_read;
        CData/*0:0*/ cpu_top__DOT__dmem_write;
        CData/*0:0*/ cpu_top__DOT__dmem_ready;
        CData/*0:0*/ cpu_top__DOT__pipeline_stall;
        CData/*0:0*/ cpu_top__DOT__if_inst_valid;
        CData/*0:0*/ cpu_top__DOT__if_inst_buffer_empty;
        CData/*0:0*/ cpu_top__DOT__if_inst_buffer_full;
        CData/*0:0*/ cpu_top__DOT__id_is_equal;
        CData/*0:0*/ cpu_top__DOT__id_reg_write;
        CData/*0:0*/ cpu_top__DOT__id_mem_read;
        CData/*0:0*/ cpu_top__DOT__id_mem_write;
        CData/*4:0*/ cpu_top__DOT__id_alu_op;
        CData/*0:0*/ cpu_top__DOT__id_has_imm;
        CData/*1:0*/ cpu_top__DOT__id_imm_type;
        CData/*1:0*/ cpu_top__DOT__id_pc_sel;
        CData/*0:0*/ cpu_top__DOT__id_is_load;
        CData/*4:0*/ cpu_top__DOT__id_rd;
        CData/*4:0*/ cpu_top__DOT__id_rs1;
        CData/*4:0*/ cpu_top__DOT__id_rs2;
        CData/*0:0*/ cpu_top__DOT__idex_reg_write;
        CData/*0:0*/ cpu_top__DOT__idex_mem_read;
        CData/*0:0*/ cpu_top__DOT__idex_mem_write;
        CData/*3:0*/ cpu_top__DOT__idex_alu_op;
        CData/*4:0*/ cpu_top__DOT__idex_rd;
        CData/*4:0*/ cpu_top__DOT__idex_rs1;
        CData/*4:0*/ cpu_top__DOT__idex_rs2;
        CData/*0:0*/ cpu_top__DOT__exmm_reg_write;
        CData/*0:0*/ cpu_top__DOT__exmm_mem_read;
        CData/*0:0*/ cpu_top__DOT__exmm_mem_write;
        CData/*4:0*/ cpu_top__DOT__exmm_rd;
        CData/*4:0*/ cpu_top__DOT__mm_rd;
        CData/*0:0*/ cpu_top__DOT__mm_reg_write;
        CData/*4:0*/ cpu_top__DOT__ex_forward_rd;
        CData/*4:0*/ cpu_top__DOT__mm_forward_rd;
        CData/*4:0*/ cpu_top__DOT__mm_mem_forward_rd;
        CData/*0:0*/ cpu_top__DOT__gpu_write_en;
        CData/*4:0*/ cpu_top__DOT__gpu_write_addr;
        CData/*4:0*/ cpu_top__DOT__gpu_read_addr;
        CData/*0:0*/ cpu_top__DOT__load_stall;
        CData/*0:0*/ cpu_top__DOT__global_stall;
        CData/*0:0*/ cpu_top__DOT__branch_taken;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__reset;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__stall;
        CData/*1:0*/ cpu_top__DOT__if_stage__DOT__pc_sel;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__inst_valid;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__inst_buffer_empty;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__inst_buffer_full;
        CData/*1:0*/ cpu_top__DOT__if_stage__DOT__M1__DOT__sel;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__M2__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__M2__DOT__reset;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__M2__DOT__stall;
    };
    struct {
        CData/*1:0*/ cpu_top__DOT__if_stage__DOT__M3__DOT__pc_sel;
        CData/*0:0*/ cpu_top__DOT__if_stage__DOT__M3__DOT__inst_valid;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__reset;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__interrupt;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stall;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__w_en;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__w_en_gpu;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__has_imm;
        CData/*1:0*/ cpu_top__DOT__id_stage__DOT__imm_type;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__load_rd;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__is_load;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__w_rd;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__w_rd_gpu;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__rs_gpu;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__ex_pro_rs;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__mm_pro_rs;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__mm_mem_rs;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__is_equal;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__inst_buffer_empty;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__inst_buffer_full;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__load_stall;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__reg_stall;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__rs_equality__DOT__is_equal;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__load_stall_check__DOT__load_rd;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__load_stall_check__DOT__is_load;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__load_stall_check__DOT__rs1_addr;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__load_stall_check__DOT__rs2_addr;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__load_stall_check__DOT__stall;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__reset;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__stall;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__inst_buffer_empty;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__inst_buffer_full;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__reset;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__write_en;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__is_empty;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__is_full;
        CData/*3:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__write_ptr;
        CData/*3:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__read_ptr;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__is_empty_flag;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__is_full_flag;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__lower_bits_equal;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__upper_bit_equal;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__reset;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__interrupt;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__write_addr_cpu;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__write_addr_gpu;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__write_en_cpu;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__write_en_gpu;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__read_addr_a;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__read_addr_b;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__read_addr_gpu;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__write_en_main;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__reset;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__write_addr;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__write_en;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__read_addr_a;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__read_addr_b;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__reset;
    };
    struct {
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__write_addr;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__write_en;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__read_addr_a;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__read_addr_b;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__reset;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__write_addr;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__write_en;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__read_addr;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__a_out__DOT__sel;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__b_out__DOT__sel;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__file_out_rs;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__ex_pro_rs;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__mm_pro_rs;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__mm_mem_rs;
        CData/*1:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__bypass_sel;
        CData/*1:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__bypass_selection__DOT__sel;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__file_out_rs;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__ex_pro_rs;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__mm_pro_rs;
        CData/*4:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__mm_mem_rs;
        CData/*1:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__bypass_sel;
        CData/*1:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__bypass_selection__DOT__sel;
        CData/*1:0*/ cpu_top__DOT__id_stage__DOT__gen_imme__DOT__imm_type;
        CData/*0:0*/ cpu_top__DOT__id_stage__DOT__b_mux__DOT__sel;
        CData/*0:0*/ cpu_top__DOT__idex_reg__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__idex_reg__DOT__rst;
        CData/*0:0*/ cpu_top__DOT__idex_reg__DOT__reg_write_in;
        CData/*0:0*/ cpu_top__DOT__idex_reg__DOT__mem_read_in;
        CData/*0:0*/ cpu_top__DOT__idex_reg__DOT__mem_write_in;
        CData/*3:0*/ cpu_top__DOT__idex_reg__DOT__alu_op_in;
        CData/*4:0*/ cpu_top__DOT__idex_reg__DOT__rd_in;
        CData/*4:0*/ cpu_top__DOT__idex_reg__DOT__rs1_in;
        CData/*4:0*/ cpu_top__DOT__idex_reg__DOT__rs2_in;
        CData/*0:0*/ cpu_top__DOT__idex_reg__DOT__reg_write_out;
        CData/*0:0*/ cpu_top__DOT__idex_reg__DOT__mem_read_out;
        CData/*0:0*/ cpu_top__DOT__idex_reg__DOT__mem_write_out;
        CData/*3:0*/ cpu_top__DOT__idex_reg__DOT__alu_op_out;
        CData/*4:0*/ cpu_top__DOT__idex_reg__DOT__rd_out;
        CData/*4:0*/ cpu_top__DOT__idex_reg__DOT__rs1_out;
        CData/*4:0*/ cpu_top__DOT__idex_reg__DOT__rs2_out;
        CData/*4:0*/ cpu_top__DOT__ex_stage__DOT__ealuc;
        CData/*0:0*/ cpu_top__DOT__ex_stage__DOT__ecall;
        CData/*0:0*/ cpu_top__DOT__exmm_reg__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__exmm_reg__DOT__rst;
        CData/*0:0*/ cpu_top__DOT__exmm_reg__DOT__reg_write_in;
        CData/*0:0*/ cpu_top__DOT__exmm_reg__DOT__mem_read_in;
        CData/*0:0*/ cpu_top__DOT__exmm_reg__DOT__mem_write_in;
        CData/*4:0*/ cpu_top__DOT__exmm_reg__DOT__rd_in;
        CData/*0:0*/ cpu_top__DOT__exmm_reg__DOT__reg_write_out;
        CData/*0:0*/ cpu_top__DOT__exmm_reg__DOT__mem_read_out;
        CData/*0:0*/ cpu_top__DOT__exmm_reg__DOT__mem_write_out;
        CData/*4:0*/ cpu_top__DOT__exmm_reg__DOT__rd_out;
        CData/*0:0*/ cpu_top__DOT__mm_stage_inst__DOT__clk;
        CData/*0:0*/ cpu_top__DOT__mm_stage_inst__DOT__rst;
        CData/*4:0*/ cpu_top__DOT__mm_stage_inst__DOT__ex_mem_rd;
        CData/*0:0*/ cpu_top__DOT__mm_stage_inst__DOT__ex_mem_mem_read;
        CData/*0:0*/ cpu_top__DOT__mm_stage_inst__DOT__ex_mem_mem_write;
        CData/*0:0*/ cpu_top__DOT__mm_stage_inst__DOT__ex_mem_reg_write;
        CData/*0:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_read;
        CData/*0:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_write;
        CData/*4:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_wb_rd;
        CData/*0:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_wb_reg_write;
        CData/*0:0*/ cpu_top__DOT__wb_stage__DOT__wmem2reg;
    };
    struct {
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__reset__0;
        CData/*0:0*/ __VactContinue;
        VL_IN(imem_data,31,0);
        VL_OUT(debug_inst,31,0);
        IData/*31:0*/ cpu_top__DOT__imem_data;
        IData/*31:0*/ cpu_top__DOT__debug_inst;
        IData/*31:0*/ cpu_top__DOT__if_inst;
        IData/*31:0*/ cpu_top__DOT__if_stage__DOT__d_inst_word;
        IData/*31:0*/ cpu_top__DOT__if_stage__DOT__inst_word;
        IData/*31:0*/ cpu_top__DOT__if_stage__DOT__M3__DOT__inst_word;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__inst_word;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__d_inst;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__d_inst_next;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__inst;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__inst;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__d_inst;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__d_inst_next;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__data_in;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__data_out;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__inst_curr;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__inst_next;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ cpu_top__DOT__id_stage__DOT__gen_imme__DOT__inst;
        IData/*31:0*/ __VactIterCount;
        VL_OUT64(imem_addr,63,0);
        VL_OUT64(dmem_addr,63,0);
        VL_OUT64(dmem_write_data,63,0);
        VL_IN64(dmem_read_data,63,0);
        VL_OUT64(debug_pc,63,0);
        QData/*63:0*/ cpu_top__DOT__imem_addr;
        QData/*63:0*/ cpu_top__DOT__dmem_addr;
        QData/*63:0*/ cpu_top__DOT__dmem_write_data;
        QData/*63:0*/ cpu_top__DOT__dmem_read_data;
        QData/*63:0*/ cpu_top__DOT__debug_pc;
        QData/*63:0*/ cpu_top__DOT__if_pc;
        QData/*63:0*/ cpu_top__DOT__if_pc4;
        QData/*63:0*/ cpu_top__DOT__id_read_out_gpu;
        QData/*63:0*/ cpu_top__DOT__id_read_out_a;
        QData/*63:0*/ cpu_top__DOT__id_read_out_b;
        QData/*63:0*/ cpu_top__DOT__id_bra_addr;
        QData/*63:0*/ cpu_top__DOT__id_jal_addr;
        QData/*63:0*/ cpu_top__DOT__id_jar_addr;
        QData/*63:0*/ cpu_top__DOT__idex_rs1_data;
        QData/*63:0*/ cpu_top__DOT__idex_rs2_data;
        QData/*63:0*/ cpu_top__DOT__idex_imm;
        QData/*63:0*/ cpu_top__DOT__ex_alu_result;
        QData/*63:0*/ cpu_top__DOT__exmm_alu_result;
        QData/*63:0*/ cpu_top__DOT__exmm_write_data;
        QData/*63:0*/ cpu_top__DOT__mm_mem_data;
        QData/*63:0*/ cpu_top__DOT__mm_alu_result;
        QData/*63:0*/ cpu_top__DOT__wb_data;
        QData/*63:0*/ cpu_top__DOT__ex_forward_data;
        QData/*63:0*/ cpu_top__DOT__mm_forward_data;
        QData/*63:0*/ cpu_top__DOT__mm_mem_forward_data;
        QData/*63:0*/ cpu_top__DOT__gpu_write_data;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__bra_addr;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__jal_addr;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__jar_addr;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__d_pc;
    };
    struct {
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__d_pc4;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__pc_next;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__pc_curr;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__M1__DOT__data_out;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__M2__DOT__pc_next;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__M2__DOT__pc_reg;
        QData/*63:0*/ cpu_top__DOT__if_stage__DOT__M3__DOT__pc;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__pc4;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__pc;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__w_result;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__w_result_gpu;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__ex_pro;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__mm_pro;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__mm_mem;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__read_out_gpu;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__read_out_a;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__read_out_b;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__bra_addr;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__jal_addr;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__jar_addr;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__d_pc;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__d_pc4;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__a_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__a_file_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__b_file_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__rs_equality__DOT__data_a;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__rs_equality__DOT__data_b;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__pc;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__data_a;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__bra_addr;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__jal_addr;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__jalr_addr;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__bra_offset;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__jal_offset;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__jalr_offset;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__dest;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__pc4;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__pc;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__d_pc4;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__d_pc;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__pc4_reg;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__pc_reg;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__data_in_cpu;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__data_in_gpu;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__data_out_a;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__data_out_b;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__data_out_gpu;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__data_in;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__data_out_a;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__data_out_b;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__data_in;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__data_out_a;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__data_out_b;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__data_in;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__data_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__a_out__DOT__data_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__b_out__DOT__data_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__file_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__ex_pro;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__mm_pro;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__mm_mem;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__bypass_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__bypass_selection__DOT__data_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__file_out;
    };
    struct {
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__ex_pro;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__mm_pro;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__mm_mem;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__bypass_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__bypass_selection__DOT__data_out;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__gen_imme__DOT__imm;
        QData/*63:0*/ cpu_top__DOT__id_stage__DOT__b_mux__DOT__data_out;
        QData/*63:0*/ cpu_top__DOT__idex_reg__DOT__rs1_data_in;
        QData/*63:0*/ cpu_top__DOT__idex_reg__DOT__rs2_data_in;
        QData/*63:0*/ cpu_top__DOT__idex_reg__DOT__imm_in;
        QData/*63:0*/ cpu_top__DOT__idex_reg__DOT__rs1_data_out;
        QData/*63:0*/ cpu_top__DOT__idex_reg__DOT__rs2_data_out;
        QData/*63:0*/ cpu_top__DOT__idex_reg__DOT__imm_out;
        QData/*63:0*/ cpu_top__DOT__ex_stage__DOT__ea;
        QData/*63:0*/ cpu_top__DOT__ex_stage__DOT__eb;
        QData/*63:0*/ cpu_top__DOT__ex_stage__DOT__epc4;
        QData/*63:0*/ cpu_top__DOT__ex_stage__DOT__eal;
        QData/*63:0*/ cpu_top__DOT__ex_stage__DOT__ealu;
        QData/*63:0*/ cpu_top__DOT__exmm_reg__DOT__alu_result_in;
        QData/*63:0*/ cpu_top__DOT__exmm_reg__DOT__write_data_in;
        QData/*63:0*/ cpu_top__DOT__exmm_reg__DOT__alu_result_out;
        QData/*63:0*/ cpu_top__DOT__exmm_reg__DOT__write_data_out;
        QData/*63:0*/ cpu_top__DOT__mm_stage_inst__DOT__ex_mem_alu_result;
        QData/*63:0*/ cpu_top__DOT__mm_stage_inst__DOT__ex_mem_write_data;
        QData/*63:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_addr;
        QData/*63:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_write_data;
        QData/*63:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_read_data;
        QData/*63:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_wb_mem_data;
        QData/*63:0*/ cpu_top__DOT__mm_stage_inst__DOT__mem_wb_alu_result;
        QData/*63:0*/ cpu_top__DOT__wb_stage__DOT__walu;
        QData/*63:0*/ cpu_top__DOT__wb_stage__DOT__wmem;
        QData/*63:0*/ cpu_top__DOT__wb_stage__DOT__wdata;
        VlUnpacked<QData/*63:0*/, 4> cpu_top__DOT__if_stage__DOT__pc_next_options;
        VlUnpacked<QData/*63:0*/, 4> cpu_top__DOT__if_stage__DOT__M1__DOT__data_in;
        VlUnpacked<QData/*63:0*/, 2> cpu_top__DOT__id_stage__DOT__b_out_options;
        VlUnpacked<IData/*31:0*/, 8> cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__inst_buffer;
        VlUnpacked<QData/*63:0*/, 2> cpu_top__DOT__id_stage__DOT__register_file__DOT__data_out_a_options;
        VlUnpacked<QData/*63:0*/, 2> cpu_top__DOT__id_stage__DOT__register_file__DOT__data_out_b_options;
        VlUnpacked<QData/*63:0*/, 32> cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__registers;
        VlUnpacked<QData/*63:0*/, 32> cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__registers;
        VlUnpacked<QData/*63:0*/, 32> cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__registers;
        VlUnpacked<QData/*63:0*/, 2> cpu_top__DOT__id_stage__DOT__register_file__DOT__a_out__DOT__data_in;
        VlUnpacked<QData/*63:0*/, 2> cpu_top__DOT__id_stage__DOT__register_file__DOT__b_out__DOT__data_in;
        VlUnpacked<QData/*63:0*/, 4> cpu_top__DOT__id_stage__DOT__a_bypass__DOT__bypass_options;
        VlUnpacked<QData/*63:0*/, 4> cpu_top__DOT__id_stage__DOT__a_bypass__DOT__bypass_selection__DOT__data_in;
        VlUnpacked<QData/*63:0*/, 4> cpu_top__DOT__id_stage__DOT__b_bypass__DOT__bypass_options;
        VlUnpacked<QData/*63:0*/, 4> cpu_top__DOT__id_stage__DOT__b_bypass__DOT__bypass_selection__DOT__data_in;
        VlUnpacked<QData/*63:0*/, 2> cpu_top__DOT__id_stage__DOT__b_mux__DOT__data_in;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ cpu_top__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__INST_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__PC_TYPE_NUM = 4U;
    static constexpr IData/*31:0*/ cpu_top__DOT__IMM_TYPE_NUM = 4U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__INST_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__PC_TYPE_NUM = 4U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__M1__DOT__INPUT_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__M1__DOT__INPUT_NUM = 4U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__M2__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__M3__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__M3__DOT__INST_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__if_stage__DOT__M3__DOT__PC_TYPE_NUM = 4U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__INST_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__rs_equality__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__branch_addrs__DOT__INST_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__load_stall_check__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__load_stall_check__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__INST_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__INST_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__stage2__DOT__insts__DOT__BUFFER_DEPTH = 8U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__main__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__shadow__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__gpu__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__a_out__DOT__INPUT_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__a_out__DOT__INPUT_NUM = 2U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__b_out__DOT__INPUT_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__register_file__DOT__b_out__DOT__INPUT_NUM = 2U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__bypass_selection__DOT__INPUT_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__a_bypass__DOT__bypass_selection__DOT__INPUT_NUM = 4U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__REG_NUM = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__bypass_selection__DOT__INPUT_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__b_bypass__DOT__bypass_selection__DOT__INPUT_NUM = 4U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__gen_imme__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__gen_imme__DOT__INST_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__gen_imme__DOT__IMM_TYPE_NUM = 4U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__b_mux__DOT__INPUT_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__id_stage__DOT__b_mux__DOT__INPUT_NUM = 2U;
    static constexpr IData/*31:0*/ cpu_top__DOT__idex_reg__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__ex_stage__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__exmm_reg__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__mm_stage_inst__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__mm_stage_inst__DOT__ADDR_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ cpu_top__DOT__wb_stage__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr QData/*63:0*/ cpu_top__DOT__if_stage__DOT__M2__DOT__RESET_ADDR = 0ULL;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
